version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/BrowserInterop"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - RemiBou
  ignore:
  - dependency-name: Microsoft.JSInterop
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Components
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
- package-ecosystem: npm
  directory: "/test/BrowserInterop.E2ETests"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
